[package]
edition = "2021"
name = "grep"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"
crossbeam = "0.8.1"
rayon = "1.5.1"
regex = "1.5.4"
