[package]
edition = "2021"
name = "dump"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = {version = "0.3.26", features = ["color", "default"]}
